### ISSUE TITLE
MyMonero

### ISSUE THREAD

**Issue by smurfiez** [PsychicCat/monero-php#2]
Is this possible to use with mymonero.com ?  I'd love to be able to pay programtically

**Comment by PsychicCat** [comment]
No, this is only compatible with monero-wallet-rpc. 

It could be possible to take MyMonero's javascript for creating transactions and use it in a Node.js environment to communicate with MyMonero API. 

However at that point, I think it would be easier just to run your own instance of monero-wallet-rpc. 

If you're still interested in programmatically communicating with Mymonero, you can find a lot of resources here:
https://github.com/luigi1111/xmr.llcoins.net/tree/master/site/js
